
name: Build Windows Java OSGi bundles for use in Dawn

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Make Windows bindings
        env:
          PLAT_OS: win32
        run: |
          C:\msys64\usr\bin\bash.exe -lc 'export PATH=/c/msys64/mingw64/bin:/c/msys64/usr/bin:"$PATH"; cd "$GITHUB_WORKSPACE" && ./releng/build_win32_bindings.sh'

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        # if: ${{ failure() }}
        with:
          limit-access-to-actor: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: hdf5-build-win32
          path: dist/

